#ifndef _GAMEPREVIEWS_H_
#define _GAMEPREVIEWS_H_

#include <avr/pgmspace.h>

#include "fontchars.h"

const uint8_t game_previews[] PROGMEM = {
	// Tetris
	127, ' ', ' ', ' ', 127,
	127, ' ', FONT_QUARTER_BLOCK_SPACED + 0b0100, FONT_QUARTER_BLOCK_SPACED + 0b1010, 127,
	127, ' ', FONT_QUARTER_BLOCK_SPACED + 0b0001, FONT_QUARTER_BLOCK_SPACED + 0b0100, 127,
	127, FONT_QUARTER_BLOCK_SPACED + 0b1101, FONT_QUARTER_BLOCK_SPACED + 0b1000, FONT_QUARTER_BLOCK_SPACED + 0b0101, 127,
	127, FONT_QUARTER_BLOCK_SPACED + 0b0101, FONT_QUARTER_BLOCK_SPACED + 0b1010, FONT_QUARTER_BLOCK_SPACED + 0b1101, 127,
	127, FONT_QUARTER_BLOCK_SPACED + 0b1101, FONT_QUARTER_BLOCK_SPACED + 0b1111, FONT_QUARTER_BLOCK_SPACED + 0b1011, 127,
	FONT_BLOCK_100, FONT_BLOCK_100, FONT_BLOCK_100, FONT_BLOCK_100, 127,
	// Snake
	FONT_SNAKE_BODY_DOWN_RIGHT, FONT_SNAKE_BODY_HORIZONTAL, FONT_SNAKE_BODY_HORIZONTAL, FONT_SNAKE_BODY_HORIZONTAL, FONT_SNAKE_BODY_DOWN_LEFT,
	FONT_SNAKE_BODY_VERTICAL, FONT_BLOCK_100, ' ', ' ', FONT_SNAKE_BODY_VERTICAL,
	FONT_SNAKE_BODY_VERTICAL, ' ', FONT_SNAKE_BODY_DOWN_RIGHT, FONT_SNAKE_BODY_HORIZONTAL, FONT_SNAKE_BODY_UP_LEFT,
	FONT_SNAKE_BODY_VERTICAL, ' ', FONT_SNAKE_BODY_VERTICAL, ' ', FONT_BLOCK_100,
	FONT_SNAKE_BODY_VERTICAL, ' ', FONT_SNAKE_BODY_UP_RIGHT, FONT_SNAKE_BODY_HORIZONTAL, FONT_SNAKE_BODY_DOWN_LEFT,
	FONT_SNAKE_BODY_VERTICAL, FONT_BLOCK_100, ' ', ' ', FONT_SNAKE_TAIL_UP,
	FONT_SNAKE_BODY_UP_RIGHT, FONT_SNAKE_BODY_HORIZONTAL, FONT_SNAKE_BODY_HORIZONTAL, FONT_SNAKE_HEAD_RIGHT, FONT_SNAKE_FOOD,
	// Options
	FONT_ANIMATED_RECTANGLE_TOP_LEFT, FONT_ANIMATED_RECTANGLE_HORIZONTAL, FONT_ANIMATED_RECTANGLE_HORIZONTAL, FONT_ANIMATED_RECTANGLE_HORIZONTAL, FONT_ANIMATED_RECTANGLE_TOP_RIGHT,
	FONT_ANIMATED_RECTANGLE_VERTICAL, ' ', ' ', ' ', FONT_ANIMATED_RECTANGLE_VERTICAL,
	FONT_ANIMATED_RECTANGLE_VERTICAL, ' ', FONT_ARROW_UP, ' ', FONT_ANIMATED_RECTANGLE_VERTICAL,
	FONT_ANIMATED_RECTANGLE_VERTICAL, FONT_ARROW_LEFT, FONT_SUIT_HEARTS, FONT_ARROW_RIGHT, FONT_ANIMATED_RECTANGLE_VERTICAL,
	FONT_ANIMATED_RECTANGLE_VERTICAL, ' ', FONT_ARROW_DOWN, ' ', FONT_ANIMATED_RECTANGLE_VERTICAL,
	FONT_ANIMATED_RECTANGLE_VERTICAL, ' ', ' ', ' ', FONT_ANIMATED_RECTANGLE_VERTICAL,
	FONT_ANIMATED_RECTANGLE_BOTTOM_LEFT, FONT_ANIMATED_RECTANGLE_HORIZONTAL, FONT_ANIMATED_RECTANGLE_HORIZONTAL, FONT_ANIMATED_RECTANGLE_HORIZONTAL, FONT_ANIMATED_RECTANGLE_BOTTOM_RIGHT,
};

#endif
